### ISSUE TITLE
gen-snippets for stories written in typescript

### ISSUE THREAD

**Issue by jackmccloy** [rbardini/storybook-addon-playroom#32]
Thanks for the great addon! I'm curious if you (or anyone else that might be reading this) might have an example where `gen-snippets` works when stories & components are written in typescript. I spent a few hours trying to get it working with no luck.

happy to cut a branch w/ the changes, but I essentially (in the example) just updated the extensions of `main.js` and `preview.js` to `.cjs`, deleted the existing components and stories, wrote a new `.tsx` component (a simple button) and a `.tsx` story for it, updated the path in `main.cjs` to include `*.stories.tsx` files, and added `"@babel/preset-typescript",` to `babel.config.json`.

`npm run gen-snippets` does run, but 0 snippets are generated. would love to know if what i'm trying to do is possible, as an automated solution for keeping my storybook stories and playroom snippets in sync would be a big win

**Comment by rbardini** [comment]
Hi @jackmccloy! Unfortunately, I don't have a recipe to share—I haven't tried to generate snippets for a TypeScript codebase yet 😕

The snippet generator is heavily based on the [StoryShots addon](https://github.com/storybookjs/storybook/tree/next/addons/storyshots/storyshots-core), so any working TypeScript examples for it might help here. (possibly related: https://github.com/storybookjs/storybook/issues/5869)

Since you see 0 snippets generated instead of an error, it looks like no stories were loaded or processed, and `snippets` below is an empty array:

https://github.com/rbardini/storybook-addon-playroom/blob/7510d88b611b00442ae43ffbd3a1f0974d32d9bf/src/generateSnippets.tsx#L147-L172

You could try adding some logs to `node_modules/storybook-addon-playroom/dist/cjs/generateSnippets.js` to pinpoint the problem. Hope that helps, let me know if you find anything!

**Comment by rbardini** [comment]
The repository now has [TypeScript component/story examples](https://github.com/rbardini/storybook-addon-playroom/tree/master/src/stories). Here's the [Babel config](https://github.com/rbardini/storybook-addon-playroom/blob/master/.babelrc.js).

This line may have done the trick:

https://github.com/rbardini/storybook-addon-playroom/blob/adeb64ab5a98054f849d8cdc50e4dda41e94dac5/bin/sb-playroom.js#L13

**Comment by jackmccloy** [comment]
Thanks @rbardini! I appreciate the follow-up and will try it out soon 🙏
