### ISSUE TITLE
Storybook v7 with addon v4 is injecting decorators into playroom code

### ISSUE THREAD

**Issue by noranda** [rbardini/storybook-addon-playroom#47]
Thanks again for upgrading this addon to work with Storybook 7!

I am having one issue, however, that I'm wondering if it's a bug given how significant of a change Storybook 7 was. Essentially, my decorator in preview that is wrapping my stories is being injected in the playroom code, and the story itself is returning `<No Display Name />`.

Below is an example of what I'm getting:

Story:
```jsx
export const Default: Story = {
  args: {
    arrow: undefined,
    headline: 'Informational tips for customers',
    tagline: 'Here is something you should know.',
    use: 'info',
  },
};
```

Decorator:
```jsx
<EzProvider theme={theme === 'marketplace' ? stitchesMarketplaceTheme : undefined}>
  <EzThemeProvider
    theme={theme === 'marketplace' ? ezMarketplaceTheme : ezFulfillmentTheme}
  >
    <EzGlobalStyles />
    <StoryFn />
  </EzThemeProvider>
</EzProvider>
```

Playroom code:
```jsx
<EzProvider theme={undefined}>
  <EzThemeProvider theme={{...}}>
    <EzGlobalStyles />
    <No Display Name />
  </EzThemeProvider>
</EzProvider>
```

What I want is just the story code as follows:
```jsx
<EzAlert
  arrow={undefined}
  headline="Informational tips for customers"
  tagline="Here is something you should know."
  use="info"
/>
```

**Comment by noranda** [comment]
Hi @rbardini! Just checking in to see if you can confirm this bug for me. Happy to help any way I can. Thanks!

**Comment by rbardini** [comment]
Hi @noranda! Sorry I didn't get back to this earlier.

Regarding the extra decorators, you probably want to apply the Playroom decorator _first_, so that the addon won't "see" your own decorators, and therefore they don't show up in the editor. If these decorators are applied by other addons, you can try reordering your `addons` array. Otherwise, I'm not sure how to tell Storybook to apply addon decorators first—Storybook doesn't mention addon decorators in their [docs](https://storybook.js.org/docs/react/writing-stories/decorators#decorator-inheritance) 😕

One option we can consider is to add a new parameter function that receives the story's generated code, and returns a new code string to be used in Playroom. This way you could clean it up, removing any unwanted elements/lines.

As for the `No Display Name`, that means [react-element-to-jsx-string](https://github.com/algolia/react-element-to-jsx-string) could not find the right display name for your element. This can happen, for example, if your code is minified, and (display) names stripped out. You can check if [`reactElementToJSXStringOptions.displayName`](https://github.com/algolia/react-element-to-jsx-string#reactelementtojsxstringreactelement-options) can help there.

**Comment by noranda** [comment]
Thanks @rbardini!

> Regarding the extra decorators, you probably want to apply the Playroom decorator first, so that the addon won't "see" your own decorators, and therefore they don't show up in the editor.

I'm a little confused about this as I don't have any defined playroom decorators, just ones for my themes. I tried making the playroom the first addon in my `main` storybook config of addons, but that didn't change anything.

> One option we can consider is to add a new parameter function that receives the story's generated code, and returns a new code string to be used in Playroom. This way you could clean it up, removing any unwanted elements/lines.

I think this sounds like a good approach. This might make this feature more stable when dealing with future storybook upgrades as well.

> As for the No Display Name, that means [react-element-to-jsx-string](https://github.com/algolia/react-element-to-jsx-string) could not find the right display name for your element.

I do set the display name in my component and it shouldn't be stripped out anywhere as far as I can tell. This was working just fine in SB 6.5 for example. Perhaps once the decorators issue is fixed (my theme providers don't have display names), this might resolve itself.

Appreciate the help!

**Comment by rbardini** [comment]
> I'm a little confused about this as I don't have any defined playroom decorators, just ones for my themes. I tried making the playroom the first addon in my `main` storybook config of addons, but that didn't change anything.

The addon automatically adds a [decorator](https://github.com/rbardini/storybook-addon-playroom/blob/master/src/withGlobals.ts) to convert story elements into JSX strings. Looks like that decorator is running after your theme providers, so they end up in the generated code.

> I do set the display name in my component and it shouldn't be stripped out anywhere as far as I can tell.

I wonder if `<StoryFn />` is being stringified, instead of the actual `<EzAlert {...} />` element. That could explain the `<No Display Name />`, and why it doesn't have any props. For troubleshooting, could you try removing your providers, or inlining them in your stories (not as decorators), and check if `<No Display Name />` is fixed?

Alternatively, we may add a new parameter function that receives the story, and returns the target element that should become Playroom code. That's probably better than cleaning up the entire resulting string, although I'd need to check if that's feasible.

**Comment by joanrm20** [comment]
Hello @rbardini, currently we are also using the addon. We noticed similar problems while migrating our design system towards SB7. 

I briefly tested and noticed that by removing the decorators at some point we also end up with the same `<No Display Name />`.  Another example is with our `ThemeDecorator`, when it was added, the entire theme was rendered in the playroom code area as well.

As mentioned above, I haven't had much time to take a look at this, but if it helps somehow I will be doing so by the end of the week, so we can complete our migration. If there's any input from your side please let me know. 

✌🏼

**Comment by noranda** [comment]
Checking in on this again. We recently started having issues loading the playroom at all in Storybook. It seems to be an iframe issue within Storybook but I can't figure out the cause. Has there been any further support for this addon in Storybook? We really rely on this, but I understand being the sole maintainer can be difficult.

**Comment by rbardini** [comment]
Hey all, sorry for the lack of updates here. I'm working on cleaning up the backlog of my projects, and I expect this issue to be fixed soon in #53.

**Comment by rbardini** [comment]
Fix has been merged, but CI didn't release the change. Likely related to https://github.com/cycjimmy/semantic-release-action/issues/168, I hope bumping the action version solves this.

**Comment by rbardini** [comment]
[v5.0.0](https://github.com/rbardini/storybook-addon-playroom/releases/tag/v5.0.0) released, excluding global decorators by default.
