### ISSUE TITLE
Doesn't seem to support multiple exports per file.

### ISSUE THREAD

**Issue by davidx1** [rbardini/storybook-addon-playroom#5]
My Buttons file look like this:
```
export const Primary = ....
export const Secondary = ...
```

Which is consumed by my story and used like so:
```
import React from 'react';
import * as Button from './index';

export default {
  title: 'Button',
};

export const Primary = () => <Button.Primary>Primary Button</Button.Primary>;

export const WithLotsOfText = () => (
  <Button.Primary>Primary Button with lots of text</Button.Primary>
);
```

But when I switch into the playroom tag the code looks like: 
```
  <Primary>
    Primary Button
  </Primary>
```

And the page displays "Primary is not defined"

If I modify the code inside the Playroom to ` <Button.Primary>Primary Button with lots of text</Button.Primary>` Then everything works as expected.

**Comment by rbardini** [comment]
Hi @davidx1! The addon uses [`react-element-to-jsx-string`](https://github.com/algolia/react-element-to-jsx-string) to transform the rendered story into a JSX string, and that's just how elements look like from a React tree perspective.

I think Storybook's [source-loader](https://github.com/storybookjs/storybook/tree/master/lib/source-loader) might offer something closer to reality, but I haven't had time to play with that yet. #1 could also work as an escape hatch for such cases.

**Comment by rbardini** [comment]
I tried using source-loader and, even though it would solve this issue, it would create many others. Since the code would reflect exactly what's in the story, any more complex story (with function calls, outer scope references, etc) would likely break in Playroom.

Deriving the JSX string from the rendered element is safer. That said, I'd suggest a few options:

1. Use the `code` [parameter option](https://github.com/rbardini/storybook-addon-playroom#configuration) to define the exact code that should be used in Playroom:
    ```jsx
    Primary.story = {
      parameters: {
        playroom: {
          code: '<Button.Primary>Primary Button</Button.Primary>',
        },
      },
    };
    ```
2. Define a custom `displayName` algorithm via the `reactElementToJSXStringOptions` [parameter option](https://github.com/rbardini/storybook-addon-playroom#configuration) that can find the right display name:
    ```jsx
    Primary.story = {
      parameters: {
        playroom: {
          reactElementToJSXStringOptions: {
            displayName: element => ...
          },
        },
      },
    };
    ```
3. Define specific `displayName` strings for components that are imported from named exports:
    ```jsx
    Primary.displayName = 'Button.Primary';
    ```

Closing this issue now, but feel free to reopen it if none of these options work 🙂
